got message from server
seunomonije/google-step-2020 pull request #5
Opened 2020-06-01 20:35 UTC by seunomonije

From the walkthrough

2020-06-01 20:50 UTC, jessicaslaughter commented
Did you mean to make this PR a merge into the master branch instead of the seun2 branch or are you going to do a larger merge from seun2 into master later?

2020-06-01 20:51 UTC, jessicaslaughter requested changes

2020-06-01 20:51 UTC, jessicaslaughter commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +
nit: remove blank line

2020-06-01 20:51 UTC, jessicaslaughter commented on portfolio/src/main/webapp/script.js
> +}
nit: new line at EOF

2020-06-01 20:51 UTC, jessicaslaughter commented on portfolio/src/main/webapp/script.js
> +async function getFromServer(){
nit: there should be a space before the curly brace

2020-06-01 20:56 UTC, seunomonije commented
Was gonna do all the server-side on this branch little by little while waiting for seun2 to be ready, then once seun2 was ready, merge server-side into seun2, then seun2 into master

2020-06-01 22:09 UTC, jessicaslaughter commented
Even though you're doing all server-side work on this branch, you should still create a separate PR every time you want us to review new work. Once a PR has been sent out for review, you shouldn't add any new functionality to it since we're actively reviewing the original code. So instead of committing new work to a PR that's already being reviewed, you should create a new one and add us as reviewers once it's in a state that you want it to be reviewed.

2020-06-01 22:10 UTC, jessicaslaughter commented
If you want us to wait on reviewing this one until you think it's got everything you want in it (while keeping it small), you can just remove us from the reviewers list and we'll wait!

2020-06-01 22:16 UTC, seunomonije commented
Ah ok I see thank you

2020-06-01 22:18 UTC, seunomonije commented
So I'm gonna have to have a bunch of branches and then delete them once I'm done right? It also makes sense with rebasing now

2020-06-01 22:30 UTC, jpnickolas requested changes

2020-06-01 22:30 UTC, geekster777 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    }
Private functions should get at the bottom of the file after all public files.

2020-06-01 22:30 UTC, geekster777 commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        messages.add(input);    // adds to array
Only add one space after the semicolon but before the comment.

2020-06-01 22:30 UTC, geekster777 commented on portfolio/src/main/webapp/script.js
> +    console.log(value);
remove debug statement

2020-06-01 22:37 UTC, jessicaslaughter commented
Yup! Ideally you'd have a branch 1 that points to master with some changes, and another branch 2 that points to branch 1 with different changes, and each branch eventually has a PR with all its commits. Once the branch 1 PR is reviewed and accepted, you push it to master, fix any merge conflicts in branch 2, and rebase that branch 2 to point to master.

2020-06-01 23:17 UTC, jessicaslaughter requested changes

2020-06-01 23:17 UTC, jessicaslaughter commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +    */
The asterisks should be aligned vertically, and the second line of the comment should line up with the top line on the left (there shouldn't be extra white space between the asterisk and that text)

2020-06-01 23:17 UTC, jessicaslaughter commented on portfolio/src/main/java/com/google/sps/servlets/DataServlet.java
> +        return defaultValue;
return statement should be indented

2020-06-01 23:59 UTC, jessicaslaughter approved these changes

2020-06-02 00:00 UTC, jpnickolas approved these changes

2020-06-05 17:53 UTC, merged